name: "Terraform Destroy"
on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  BUCKET_tf_STATE: ${{ secrets.BUCKET_tf_STATE }}
  AWS_REGION: us-east-1

jobs:
  destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -backend-config=bucket=${BUCKET_tf_STATE}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
